apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managed-syslog

resources:
  - namespace.yaml
  - prometheus-helmchart.yaml

commonLabels:
  app: prometheus
  managed-by: gitops