apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: managed-syslog

resources:
  # Base resources embedded in overlay for Fleet path resolution
  # Note: namespace.yaml removed - managed-syslog namespace will be created by base
  - prometheus-helmchart.yaml

commonLabels:
  app: prometheus
  managed-by: gitops